---
#
# Copyright 2014 Major Hayden
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

# example: 
# Just run the check
# ansible-playbook -i hosts playbookv2.yml -s -C -e "backup=yes"

#  Run the fix
# ansible-playbook -i hosts playbookv2.yml -s -e "backup=yes"

# Backup the conf
# ansible-playbook -i hosts playbookv2.yml -s -e "backup=yes"

# Rollback the conf
# ansible-playbook -i hosts playbookv2.yml -s -e "rollback=yes"

- hosts: all
#  accelerate: true
  user: centos
  vars: 
    default_auid: 1000
    company_name: Linuxdict
    backup: yes
    rollback: no
  roles:
    - cis2
