---
#
# Copyright 2014 Major Hayden
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

  - name: 4.2.1 Ensure rsyslog software installed (Scored)
    yum: >
      name=rsyslog
      state=present
    tags:
      - scored
      - section4.2
      - section4.2.1

  - name: 4.2.1.1 Ensure rsyslog Service is enabled (Scored)
    service: >
      name=rsyslog
      enabled=yes
      state=started
    tags:
      - scored
      - section4.2
      - section4.2.1
      - section4.2.1.1

  - name: 4.2.1.2 Ensure logging is configured (Not Scored)
    copy: >
      src=etc/rsyslog.conf
      dest=/etc/rsyslog.conf
      owner=root
      group=root
      mode=0644
    notify: Reload rsyslog
    tags:
      - notscored
      - section4.2
      - section4.2.1
      - section4.2.1.2

  - name: 4.2.1.3 Ensure rsyslog default file permissions configured (Scored)
    file: >
      path=/var/log/{{ item }}
      state=touch
      owner=root
      group=wheel
      mode=0640
    with_items:
        - messages
        - kern.log
        - daemon.log
        - syslog
        - unused.log
    notify: Reload rsyslog
    tags:
      - scored
      - section4.2
      - section4.2.1
      - section4.2.1.3

  - name: 4.2.1.4 Ensure rsyslog is configured to send logs to a remote log host (Scored)
    lineinfile: >
      state=present
      dest=/etc/rsyslog.conf
      regexp="^\*\.\*"
      line="*.* @@{{ rsyslog_dest }}"
    when: rsyslog_dest is defined
    notify: Reload rsyslog
    tags:
      - scored
      - section4.2
      - section4.2.1
      - section4.2.1.4

  - name: 4.2.1.5 Ensure remote rsyslog messages are only accepted on designated log hosts. (Not Scored)
    lineinfile: >
      state=present
      line="$ModLoad imtcp.so"
    when: rsyslog_host
    notify: Reload rsyslog
    tags:
      - notscored
      - section4.2
      - section4.2.1
      - section4.2.1.5

  - name: 4.2.1.5 Ensure remote rsyslog messages are only accepted on designated log hosts. (Not Scored)
    lineinfile: >
      state=present
      line="$InputTCPServerRun 514"
    when: rsyslog_host
    notify: Reload rsyslog
    tags:
      - notscored
      - section4.2
      - section4.2.1
      - section4.2.1.5

  - name: 4.2.2 Configure syslog-ng
    command: rpm -q syslog-ng
    register: syslog_ng_check
    ignore_errors: yes
    tags:
      - notscored
      - section4.2
      - section4.2.2

  - name: 4.2.2.1 Ensure syslog-ng service is enabled (Scored)
    service: >
      name=syslog-ng
      enabled=yes
      state=started
    when: syslog_ng_check.rc == 0
    tags:
      - notscored
      - section4.2
      - section4.2.2
      - section4.2.2.1

  - name: 4.2.2.2 Ensure logging is configured (Not Scored)
    copy: >
      src=etc/syslog-ng.conf
      dest=/etc/syslog-ng/syslog-ng.conf
      owner=root
      group=root
      mode=0644
    when: syslog_ng_check.rc == 0
    tags:
      - notscored
      - section4.2
      - section4.2.2
      - section4.2.2.2

  - name: 4.2.2.3 Ensure syslog-ng default file permissions configured (Scored)
    debug: "*** Will do it later"
    when: syslog_ng_check.rc == 0
    tags:
      - notscored
      - section4.2
      - section4.2.2
      - section4.2.2.3

  - name: 4.2.2.4 Ensure syslog-ng is configured to send logs to a remote log host (Not Scored)
    debug: "*** Will do it later"
    when: syslog_ng_check.rc == 0
    tags:
      - notscored
      - section4.2
      - section4.2.2
      - section4.2.2.4

  - name: 4.2.2.5 Ensure remote syslog-ng messages are only accepted on designated log hosts (Not Scored)
    debug: "*** Will do it later"
    when: syslog_ng_check.rc == 0
    tags:
      - notscored
      - section4.2
      - section4.2.2
      - section4.2.2.5

  - name: 4.2.3 Ensure rsyslog or syslog-ng is installed (Scored)
    debug: "*** Will do it later"
    when: syslog_ng_check.rc == 0
    tags:
      - scored
      - section4.2
      - section4.2.3

  - name: 4.2.4 Ensure permissions on all logfiles are configured (Scored)
#    shell: find /var/log -type f -exec chmod g-wx,o-rwx {} +
    debug: "*** Be careful with Production system. "
    tags:
      - scored
      - section4.2
      - section4.2.4

  - name: 4.3 Ensure logrotate is configured (Not Scored)
    debug: "*** Will do it later"
    tags:
      - notscored
      - section4.3
