---
#
# Copyright 2014 Major Hayden
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

  - name: 3.1.1 Ensure IP forwarding is disabled (Scored)
    sysctl: >
      name={{ item }}
      value=0
      state=present
    with_items: 
      - net.ipv4.ip_forward
    tags:
      - scored
      - section3.1
      - section3.1.1

  - name: 3.1.1 Ensure IP route flush is disabled (Scored)
    sysctl: >
      name=net.ipv4.route.flush
      value=1
      state=present
    tags:
      - scored
      - section3.1
      - section3.1.1

  - name: 3.1.2 Ensure packet redirect sending is disabled (Scored)
    sysctl: >
      name={{ item }}
      value=0
      state=present
    with_items: 
      - net.ipv4.conf.all.send_redirects
      - net.ipv4.conf.default.send_redirects
    tags:
      - scored
      - section3.1
      - section3.1.2

  - name: 3.2.1 Ensure source routed packets are not accepted (Scored)
    sysctl: >
      name={{ item }}
      value=0
      state=present
    with_items: 
      - net.ipv4.conf.all.accept_source_route
      - net.ipv4.conf.default.accept_source_route
    tags:
      - scored
      - section3.2
      - section3.2.1

  - name: 3.2.2 Ensure ICMP redirects are not accepted (Scored)
    sysctl: >
      name={{ item }}
      value=0
      state=present
    with_items: 
      - net.ipv4.conf.all.accept_redirects
      - net.ipv4.conf.default.accept_redirects
    tags:
      - scored
      - section3.2
      - section3.2.2

  - name: 3.2.3 Ensure secure ICMP redirects are not accepted (Scored)
    sysctl: >
      name={{ item }}
      value=0
      state=present
    with_items: 
      - net.ipv4.conf.all.secure_redirects
      - net.ipv4.conf.default.secure_redirects
    tags:
      - scored
      - section3.2
      - section3.2.3

  - name: 3.2.4 Ensure suspicious packets are logged (Scored)
    sysctl: >
      name={{ item }}
      value=1
      state=present
    with_items: 
      - net.ipv4.conf.all.log_martians
      - net.ipv4.conf.default.log_martians
      - net.ipv4.route.flush
    tags:
      - scored
      - section3.2
      - section3.2.4

  - name: 3.2.5 Ensure broadcast ICMP requests are ignored (Scored)
    sysctl: >
      name={{ item }}
      value=1
      state=present
    with_items: 
      - net.ipv4.icmp_echo_ignore_broadcasts
      - net.ipv4.route.flush
    tags:
      - scored
      - section3.2
      - section3.2.5

  - name: 3.2.6 Ensure bogus ICMP responses are ignored (Scored)
    sysctl: >
      name={{ item }}
      value=1
      state=present
    with_items: 
      - net.ipv4.icmp_ignore_bogus_error_responses
      - net.ipv4.route.flush
    tags:
      - scored
      - section3.2
      - section3.2.6

  - name: 3.2.7 Ensure Reverse Path Filtering is enabled (Scored)
    sysctl: >
      name={{ item }}
      value=1
      state=present
    with_items: 
      - net.ipv4.conf.all.rp_filter
      - net.ipv4.conf.default.rp_filter
      - net.ipv4.route.flush
    tags:
      - scored
      - section3.2
      - section3.2.7

  - name: 3.2.8 Ensure TCP SYN Cookies is enabled (Scored)
    sysctl: >
      name={{ item }}
      value=1
      state=present
    with_items: 
      - net.ipv4.tcp_syncookies
      - net.ipv4.route.flush
    tags:
      - scored
      - section3.2
      - section3.2.7

  - name: 3.3.1 Ensure IPv6 router advertisements are not accepted (Scored)
    sysctl: >
      name={{ item }}
      value=0
      state=present
    with_items: 
      - net.ipv6.conf.all.accept_ra
      - net.ipv6.conf.default.accept_ra
    tags:
      - scored
      - section3.3
      - section3.3.1

  - name: 3.3.2 Ensure IPv6 redirects are not accepted (Scored)
    sysctl: >
      name={{ item }}
      value=0
      state=present
    with_items: 
      - net.ipv6.conf.all.accept_redirects
      - net.ipv6.conf.default.accept_redirects
    tags:
      - scored
      - section3.3
      - section3.3.2

  - name: 3.3.2 Ensure IPv6 redirects are not accepted (Scored)
    sysctl: >
      name={{ item }}
      value=0
      state=present
    with_items: 
      - net.ipv6.conf.all.accept_redirects
      - net.ipv6.conf.default.accept_redirects
    tags:
      - scored
      - section3.3
      - section3.3.2

  - name: 3.3.3 Ensure IPv6 is disabled (Not Scored)
    lineinfile: >
      state=present
      create=yes
      dest=/etc/modprobe.d/ipv6.conf
      line="options ipv6 disable=1"
    tags:
      - notscored
      - section3.3
      - section3.3.3

  - name: 3.4.1 Ensure TCP Wrappers is installed (Scored)
    yum: >
      name=tcp_wrappers
      state=present
    tags:
      - scored
      - section3.4
      - section3.4.1

  - name: 3.4.2 Ensure /etc/hosts.allow is configured (Scored)
    lineinfile: >
      state=present
      create=yes
      dest=/etc/hosts.allow
      regexp=^ALL
      line=ALL:{{ tcp_allow | default("ALL") }}
    tags:
      - notscored
      - section3.4
      - section3.4.2

  - name: 3.4.3 Ensure /etc/hosts.deny is configured (Scored)
    lineinfile: >
      state=present
      create=yes
      dest=/etc/hosts.deny
      line=ALL:ALL
    tags:
      - notscored
      - section3.4
      - section3.4.3

  - name: 3.4.4 Ensure permissions on /etc/hosts.allow are configured (Scored)
    file: >
      path=/etc/hosts.allow
      mode=0644
    tags:
      - scored
      - section3.4
      - section3.4.4

  - name: 3.4.5 Ensure permissions on /etc/hosts.deny are 644 (Scored)
    file: >
      path=/etc/hosts.deny
      mode=0644
    tags:
      - scored
      - section3.4
      - section3.4.5

  - name: 3.5.1 Ensure DCCP is disabled (Not Scored)
    lineinfile: >
      state=present
      create=yes
      dest=/etc/modprobe.d/CIS.conf
      line="install dccp /bin/true"
    tags:
      - notscored
      - section3.5
      - section3.5.1

  - name: 3.5.2 Ensure SCTP is disabled (Not Scored)
    lineinfile: >
      state=present
      create=yes
      dest=/etc/modprobe.d/CIS.conf
      line="install sctp /bin/true"
    tags:
      - notscored
      - section3.5
      - section3.5.2

  - name: 3.5.3 Ensure RDS is disabled (Not Scored)
    lineinfile: >
      state=present
      create=yes
      dest=/etc/modprobe.d/CIS.conf
      line="install rds /bin/true"
    tags:
      - notscored
      - section3.5
      - section3.5.3

  - name: 3.5.4 Ensure TIPC is disabled (Not Scored)
    lineinfile: >
      state=present
      create=yes
      dest=/etc/modprobe.d/CIS.conf
      line="install tipc /bin/true"
    tags:
      - notscored
      - section3.5
      - section3.5.4

  - name: 3.6.1 Ensure iptables is installed (Scored)
    yum: >
      name=iptables
      state=present
    tags:
      - scored
      - section3.6
      - section3.6.1

  - name: 3.6.2 - 3.6.5 Ensure default deny firewall policy (Scored)
    debug: >
      msg="*** Too dangerous for Prod system. check notes"
    tags:
      - scored
      - section3.6
      - section3.6.2
      - section3.6.3
      - section3.6.4
      - section3.6.5

  - name: 3.7 Ensure wireless interfaces are disabled (Not Scored)
    debug: >
      msg="*** If you have Wifi device for Server, disable it"
    tags:
      - notscored
      - section3.7
